import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { revenues } from "../../data/revenues";
import { customers } from "../../data/customers";

function formatCurrency(value: number) {
  return `฿${value.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function statusClass(status: string) {
  return status
    .toLowerCase()
    .replace(/\s+/g, "-");
}

export default function RevenuePage() {
  const [search, setSearch] = useState("");

  const [statusFilter, setStatusFilter] =
    useState("All");

  const [customerFilter, setCustomerFilter] =
    useState("All");

  const filteredRevenue = useMemo(() => {
    return revenues.filter((revenue) => {
      const customer = customers.find(
        (item) =>
          item.id === revenue.customerId
      );

      const searchText =
        search.toLowerCase();

      const matchesSearch =
        revenue.revenueNumber
          .toLowerCase()
          .includes(searchText) ||
        revenue.description
          .toLowerCase()
          .includes(searchText) ||
        (customer?.name
          .toLowerCase()
          .includes(searchText) ??
          false);

      const matchesStatus =
        statusFilter === "All" ||
        revenue.status === statusFilter;

      const matchesCustomer =
        customerFilter === "All" ||
        revenue.customerId ===
          customerFilter;

      return (
        matchesSearch &&
        matchesStatus &&
        matchesCustomer
      );
    });
  }, [
    search,
    statusFilter,
    customerFilter,
  ]);

  const totalRevenue = revenues
    .filter(
      (revenue) =>
        revenue.status !== "Cancelled"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.amount,
      0
    );

  const totalTax = revenues
    .filter(
      (revenue) =>
        revenue.status !== "Cancelled"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.taxAmount,
      0
    );

  const totalWithTax = revenues
    .filter(
      (revenue) =>
        revenue.status !== "Cancelled"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.totalAmount,
      0
    );

  const paidRevenue = revenues
    .filter(
      (revenue) =>
        revenue.status === "Paid"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.totalAmount,
      0
    );

  const pendingRevenue = revenues
    .filter(
      (revenue) =>
        revenue.status === "Pending"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.totalAmount,
      0
    );

  const invoicedRevenue = revenues
    .filter(
      (revenue) =>
        revenue.status === "Invoiced"
    )
    .reduce(
      (sum, revenue) =>
        sum + revenue.totalAmount,
      0
    );

  return (
    <div>
      {/* Header */}
      <div
        style={{
          display: "flex",
          justifyContent:
            "space-between",
          alignItems: "center",
          marginBottom: 24,
        }}
      >
        <div>
          <h1>Revenue</h1>

          <p
            style={{
              color: "#6b7280",
            }}
          >
            Track transportation revenue
            generated by the operation.
          </p>
        </div>

        <button
          onClick={() =>
            alert(
              "Create Revenue - demo only"
            )
          }
        >
          + Create Revenue
        </button>
      </div>

      {/* KPI Cards */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns:
            "repeat(5, minmax(0, 1fr))",
          gap: 16,
          marginBottom: 24,
        }}
      >
        <div className="card">
          <p>Net Revenue</p>

          <h2>
            {formatCurrency(
              totalRevenue
            )}
          </h2>
        </div>

        <div className="card">
          <p>Paid</p>

          <h2>
            {formatCurrency(
              paidRevenue
            )}
          </h2>
        </div>

        <div className="card">
          <p>Invoiced</p>

          <h2>
            {formatCurrency(
              invoicedRevenue
            )}
          </h2>
        </div>

        <div className="card">
          <p>Pending</p>

          <h2>
            {formatCurrency(
              pendingRevenue
            )}
          </h2>
        </div>

        <div className="card">
          <p>Transactions</p>

          <h2>
            {revenues.length}
          </h2>
        </div>
      </div>

      {/* Financial Summary */}
      <div
        className="card"
        style={{
          marginBottom: 24,
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(3, 1fr)",
            gap: 24,
          }}
        >
          <div>
            <p>Revenue Before VAT</p>

            <h2>
              {formatCurrency(
                totalRevenue
              )}
            </h2>
          </div>

          <div>
            <p>VAT</p>

            <h2>
              {formatCurrency(totalTax)}
            </h2>
          </div>

          <div>
            <p>Total Including VAT</p>

            <h2>
              {formatCurrency(
                totalWithTax
              )}
            </h2>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div
        className="card"
        style={{
          marginBottom: 24,
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "2fr 1fr 1fr",
            gap: 16,
          }}
        >
          <div>
            <label>Search</label>

            <input
              type="text"
              placeholder="Search revenue, customer..."
              value={search}
              onChange={(event) =>
                setSearch(
                  event.target.value
                )
              }
              style={{
                width: "100%",
                padding: 10,
                marginTop: 6,
                boxSizing: "border-box",
              }}
            />
          </div>

          <div>
            <label>Status</label>

            <select
              value={statusFilter}
              onChange={(event) =>
                setStatusFilter(
                  event.target.value
                )
              }
              style={{
                width: "100%",
                padding: 10,
                marginTop: 6,
              }}
            >
              <option value="All">
                All Statuses
              </option>

              <option value="Pending">
                Pending
              </option>

              <option value="Invoiced">
                Invoiced
              </option>

              <option value="Paid">
                Paid
              </option>

              <option value="Cancelled">
                Cancelled
              </option>
            </select>
          </div>

          <div>
            <label>Customer</label>

            <select
              value={customerFilter}
              onChange={(event) =>
                setCustomerFilter(
                  event.target.value
                )
              }
              style={{
                width: "100%",
                padding: 10,
                marginTop: 6,
              }}
            >
              <option value="All">
                All Customers
              </option>

              {customers.map(
                (customer) => (
                  <option
                    key={customer.id}
                    value={customer.id}
                  >
                    {customer.name}
                  </option>
                )
              )}
            </select>
          </div>
        </div>
      </div>

      {/* Revenue Table */}
      <div className="card">
        <div
          style={{
            marginBottom: 16,
          }}
        >
          <h2>Revenue Transactions</h2>

          <p>
            {filteredRevenue.length} records
          </p>
        </div>

        <div
          style={{
            overflowX: "auto",
          }}
        >
          <table
            style={{
              width: "100%",
              borderCollapse:
                "collapse",
            }}
          >
            <thead>
              <tr>
                <th>Revenue</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Description</th>
                <th>Amount</th>
                <th>VAT</th>
                <th>Total</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {filteredRevenue.map(
                (revenue) => {
                  const customer =
                    customers.find(
                      (item) =>
                        item.id ===
                        revenue.customerId
                    );

                  return (
                    <tr
                      key={revenue.id}
                    >
                      <td>
                        <strong>
                          {
                            revenue.revenueNumber
                          }
                        </strong>
                      </td>

                      <td>
                        {revenue.date}
                      </td>

                      <td>
                        {customer?.name ??
                          revenue.customerId}
                      </td>

                      <td>
                        {revenue.description}
                      </td>

                      <td>
                        {formatCurrency(
                          revenue.amount
                        )}
                      </td>

                      <td>
                        {formatCurrency(
                          revenue.taxAmount
                        )}
                      </td>

                      <td>
                        <strong>
                          {formatCurrency(
                            revenue.totalAmount
                          )}
                        </strong>
                      </td>

                      <td>
                        <span
                          className={`status ${statusClass(
                            revenue.status
                          )}`}
                        >
                          {revenue.status}
                        </span>
                      </td>

                      <td>
                        <Link
                          to={`/finance/revenue/${revenue.id}`}
                        >
                          <button>
                            View
                          </button>
                        </Link>
                      </td>
                    </tr>
                  );
                }
              )}
            </tbody>
          </table>
        </div>

        {filteredRevenue.length ===
          0 && (
          <div
            style={{
              textAlign: "center",
              padding: 40,
              color: "#6b7280",
            }}
          >
            No revenue records found.
          </div>
        )}
      </div>
    </div>
  );
}
